---
language: python
services: docker
env:
  global:
    - ROLE_NAME: common
install:
  - pip install molecule yamllint ansible-lint docker
before_script:
  - cd ../
  - git clone --depth=1 https://github.com/wate/ansible-role-repo-epel.git repo-epel
  - mv ansible-role-$ROLE_NAME $ROLE_NAME
  - cd $ROLE_NAME
script:
  - molecule test
notifications:
  email: false
  slack:
    secure: B5155TyisnIQdWsuidMneZW2j0ShUl6sadQFidTBV21O0yo3qkGHfJMd0cUi9MPsbsQQON6KRtp9lztADG4CzKAO2yZSxsp3cmA4ZRPM2VxHcnchiHMEonBEjXdgWpFXbgULPR9nqyRjs8aO3mLM86mqeWda7cXxsQQVBsoyqODvcq3o1NJkJJJRcokW9yUkXcC3p5J/tJlJUCIAWnaUX2rRHozHdCcQ13y6DgZDvT4jJMXwZru+cSMN6naukT0MtoO3rAhEoJ0OmJefnc2YjHDZDYrTkVf26e5yy2bOqiq91JMUKN1GQcoTrsBMbdIaglZAJN46M5k54BzMOMf6pKGh7zlwaYmJJaE0QF9OjaU/zjb3iYdzUKYmm5AyaU3sb6AzaZCjM+NX+W8wic0W/XXWTaVdqLbQ6uCRz6ugDWmSV/8Ny4DPA5PJk9ezMrHY5ny7xvELrha3cY2tcmCyTrQhS7WDf4C9gVbiMTt7nsNsYWgN95o8xMC03G/pO3MPa+gvdnfQ82RQkFRg+2zLUzc4mIxGuzIT6c51YKYIc10OjIltwfEPIzFHUsoenotCcGBqmAOfoLvEGiXIEOxR25ZC/eGvbZCNvjsidXILoICv6lAowDFWmHXRoSXQKnnosWzuLUVd8VdfQ4RPEfgRLsVk3DrTDqeNvQ7wIeUPPeE=
