# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: '3'
tasks:
  default:
    desc: Run Molecule tests for default scenario
    cmd: molecule test
  glances:
    desc: Run Molecule tests for glances scenario
    cmd: molecule test -s glances
  all:
    desc: Run Molecule tests for all scenarios (sequential)
    cmds:
      - task: default
      - task: glances
