---
- name: Get latest release
  ansible.builtin.uri:
    url: https://api.github.com/repos/kellyjonbrazil/jc/releases/latest
    headers:
      Accept: application/vnd.github+json
  register: latest_releases
- name: Set version variable
  ansible.builtin.set_fact:
    jc_version: "{{ latest_releases.json.tag_name }}"
- name: Set variable
  ansible.builtin.set_fact:
    package_file: jc_{{ jc_version[1:] }}-1_{{ architecture_files[ansible_facts['architecture']] }}.deb
  vars:
    architecture_files:
      x86_64: amd64
- name: Install jc
  ansible.builtin.apt:
    deb: https://github.com/kellyjonbrazil/jc/releases/download/{{ jc_version }}/{{ package_file }}
