---
- name: Get latest release
  when: jc_version | default('latest') == 'latest'
  block:
    - name: Set Github API request header
      ansible.builtin.set_fact:
        github_api_request_headers:
          Accept: application/vnd.github+json
    - name: Merge Github API Authorization request header
      ansible.builtin.set_fact:
        github_api_request_headers: "{{ github_api_request_headers | combine(merge_request_header) }}"
      vars:
        merge_request_header:
          Authorization: Bearer {{ lookup('env', 'GITHUB_TOKEN') }}
      when: lookup('env', 'GITHUB_TOKEN') | length > 0
    - name: Get jc latest release
      ansible.builtin.uri:
        url: https://api.github.com/repos/kellyjonbrazil/jc/releases/latest
        headers: "{{ github_api_request_headers }}"
      register: latest_releases
    - name: Set version variable
      ansible.builtin.set_fact:
        jc_version: "{{ latest_releases.json.tag_name }}"
- name: Set variable
  ansible.builtin.set_fact:
    package_file: jc_{{ jc_version[1:] }}-1_{{ architecture_files[ansible_facts['architecture']] }}.deb
  vars:
    architecture_files:
      x86_64: amd64
- name: Install jc
  ansible.builtin.apt:
    deb: https://github.com/kellyjonbrazil/jc/releases/download/{{ jc_version }}/{{ package_file }}
