---
- name: create backup data directory
  file:
    path: "{{ backup_dir }}"
    state: directory
    mode: "0755"
- name: create backup scripts directory
  file:
    path: "{{ backup_script_dir }}"
    state: directory
    mode: "0755"
- name: download backup script
  get_url:
    url: "{{ item.url }}"
    dest: "{{ backup_script_dir }}/{{ item.url | basename }}"
    checksum: "{{ item.checksum | default(omit) }}"
    url_username: "{{ item.auth_basic_user | default(omit) }}"
    url_password: "{{ item.auth_basic_password | default(omit) }}"
    mode: "0755"
  with_items: "{{ backup_settings|selectattr('url', 'defined') | list }}"
- name: upload backup script
  copy:
    src: "{{ item.file }}"
    dest: "{{ backup_script_dir }}/{{ item.file | basename }}"
    checksum: "{{ item.checksum | default(omit) }}"
    mode: "0755"
  loop: "{{ backup_settings | selectattr('file', 'defined') | list }}"
- name: manage backup settings
  cron:
    name: "{{ item.name }}"
    job: "{{ item.command }}"
    minute: "{{ item.minute | default(omit) }}"
    hour: "{{ item.hour | default(omit) }}"
    day: "{{ item.day | default(omit) }}"
    weekday: "{{ item.weekday | default(omit) }}"
    month: "{{ item.month | default(omit) }}"
    user: "{{ item.user | default('root') }}"
    disabled: "{{ item.disabled | default(false) }}"
    state: "{{ 'present' if item.state | default(true) else 'absent' }}"
  loop: "{{ backup_settings }}"
