---
- name: Install dependency packages
  ansible.builtin.apt:
    name:
      - parted
      - util-linux
      - e2fsprogs
      - xfsprogs
- name: Gathers hardware facts
  ansible.builtin.setup:
    gather_subset:
      - hardware
- name: Manage disk partition
  ansible.builtin.include_tasks: disk/manage_partition.yml
  vars:
    tmp_device: "{{ item[0].device }}"
    tmp_if_device_exists: "{{ item[0].if_device_exists | default(true) }}"
    tmp_partition: "{{ item[1] }}"
  loop: "{{ common_disks | subelements('partitions') }}"
- name: Gathers hardware facts
  ansible.builtin.setup:
    gather_subset:
      - hardware
