---
- name: install etckeeper
  ansible.builtin.apt:
    name: etckeeper
- name: check git repository directory
  ansible.builtin.stat:
    path: /etc/.git
  register: result
- name: etckeeper initilize
  block:
    - name: initilize etckeeper
      command: etckeeper init
      args:
        chdir: /etc
      tags:
        - skip_ansible_lint
    - name: initial commit
      command: etckeeper commit "Initial commit"
      tags:
        - skip_ansible_lint
  when: not result.stat.exists
