---
- name: Install etckeeper
  ansible.builtin.apt:
    name: etckeeper
- name: Check git repository directory
  ansible.builtin.stat:
    path: /etc/.git
  register: result
- name: Initilize etckeeper
  when: not result.stat.exists
  block:
    - name: Initilize repository
      ansible.builtin.command:
        cmd: etckeeper init
        chdir: /etc
      changed_when: true
    - name: Initial commit
      ansible.builtin.command:
        cmd: etckeeper commit "Initial commit"
      changed_when: true
