---
- name: Install etckeeper
  ansible.builtin.apt:
    name: etckeeper
- name: Check git repository directory
  ansible.builtin.stat:
    path: /etc/.git
  register: result
- name: Initilize etckeeper
  ansible.builtin.command:
    cmd: etckeeper init
    chdir: /etc
  when: not result.stat.exists
- name: Initial commit
  ansible.builtin.command:
    cmd: etckeeper commit "Initial commit"
  when: not result.stat.exists
