---
- name: Install fail2ban
  ansible.builtin.apt:
    name: fail2ban
- name: Set fail2ban setting
  ansible.builtin.blockinfile:
    path: /etc/fail2ban/jail.local
    block: "{{ fail2ban_cfg }}"
    create: true
    mode: "0644"
  notify: restart fail2ban
- name: Ensure fail2ban is active and enabled on system startup
  ansible.builtin.systemd:
    name: fail2ban
    state: started
    enabled: true
