---
- name: Install ufw
  ansible.builtin.apt:
    name: ufw
- name: Ensure ufw is active and enabled on system startup
  ansible.builtin.systemd_service:
    name: ufw
    state: started
    enabled: true
