---
- name: Install glances
  ansible.builtin.apt:
    name:
      - glances
      - python3-pip
- name: Install glances additional packages
  ansible.builtin.apt:
    name: "{{ glances_additional_packages }}"
- name: Install glances additional pip packages
  ansible.builtin.pip:
    name: "{{ glances_additional_pip_packages }}"
  when: glances_additional_pip_packages | length > 0
- name: Update glances setting
  ansible.builtin.include_tasks:
    file: glances/setting.yml
  loop: "{{ glances_setting | dict2items(key_name='name', value_name='options') }}"
  loop_control:
    loop_var: glances_setting_section
- name: Create glances systemd unit file
  ansible.builtin.template:
    src: glances/glances.service.j2
    dest: /lib/systemd/system/glances.service
    mode: "0644"
  notify: restart glances
- name: Set glances service setting
  ansible.builtin.systemd_service:
    name: glances
    state: "{{ glances_service_setting.running | ternary('started', 'stopped') }}"
    enabled: "{{ glances_service_setting.enabled }}"
- name: Ensure allow glances port
  community.general.ufw:
    port: "{{ item | string }}"
    proto: tcp
    rule: allow
  loop: "{{ glances_allow_ports }}"
