---
- name: Install japanese environment package
  ansible.builtin.apt:
    name: task-japanese
- name: Install font packages
  ansible.builtin.apt:
    name: "{{ common_japanese_fonts }}"
- name: Install other japanse fonts
  ansible.builtin.include_tasks: japanese/{{ item }}.yml
  loop: "{{ other_japanese_fonts }}"
  vars:
    other_japanese_fonts:
      - morisawa-biz-ud
  when: install_other_japanese_fonts
- name: Ensure locale exists
  community.general.locale_gen:
    name: ja_JP.UTF-8
    state: present
- name: Get system locale
  ansible.builtin.command:
    cmd: localectl status
  register: result
  changed_when: false
- name: Set locale
  ansible.builtin.command:
    cmd: localectl set-locale LANG=ja_JP.UTF-8 LANGUAGE="ja_JP:ja"
  when: "'LANG=ja_JP.UTF-8' not in result.stdout"
