---
- name: Add repository
  ansible.builtin.import_tasks: repository.yml
  tags: repository
- name: Install aptitude
  ansible.builtin.apt:
    name: aptitude
- name: Setup sudo
  ansible.builtin.import_tasks: sudo.yml
  tags: sudo
- name: Set hostname
  ansible.builtin.hostname:
    name: "{{ common_hostname }}"
  tags:
    - hostname
    - molecule-notest
- name: Change home directory permission
  ansible.builtin.file:
    path: /home
    mode: "0755"
    state: directory
- name: Install common packages
  ansible.builtin.apt:
    name: "{{ common_packages }}"
- name: Manage user skeleton directory
  ansible.builtin.import_tasks: skeleton.yml
  tags: skeleton
- name: Manage user
  ansible.builtin.import_tasks: user.yml
  tags: user
- name: Setup disk partition
  ansible.builtin.import_tasks: disk.yml
  tags: disk
- name: Setup firewall
  ansible.builtin.import_tasks: firewall.yml
  tags: firewall
- name: Setup japanese environment
  ansible.builtin.import_tasks: japanese.yml
  tags: japanese
- name: Setup etckeeper
  ansible.builtin.import_tasks: etckeeper.yml
  tags: etckeeper
- name: Setup package auto update
  ansible.builtin.import_tasks: auto_update.yml
  tags: auto_update
- name: Manage files
  ansible.builtin.import_tasks: files.yml
  tags: file
- name: Manage cron
  ansible.builtin.import_tasks: cron.yml
  tags: cron
- name: Manage log
  ansible.builtin.import_tasks: log.yml
  tags: log
- name: Setup sshd
  ansible.builtin.import_tasks: sshd.yml
  tags: sshd
- name: Setup ssh
  ansible.builtin.import_tasks: ssh.yml
  tags: ssh
- name: Setup fail2ban
  ansible.builtin.import_tasks: fail2ban.yml
  tags: fail2ban
- name: Setup swap
  ansible.builtin.import_tasks: swap.yml
  tags: swap
- name: Manage mount setting
  ansible.builtin.import_tasks: mount.yml
  tags: mount
- name: Manage backup setting
  ansible.builtin.import_tasks: backup.yml
  tags: backup
- name: Setup other utilities
  ansible.builtin.import_tasks: utilities.yml
  tags: utilities
