---
- name: setup sudo
  import_tasks: sudo.yml
  tags: sudo
- name: manage groups
  import_tasks: group.yml
  tags: group
- name: create skeleton user web directory
  file:
    path: /etc/skel/public
    mode: "0755"
    state: directory
  tags:
    - skeleton
- name: set home directory permission
  file:
    path: /home
    mode: "0755"
    state: directory
- name: install common packages
  yum:
    name: "{{ item }}"
  with_items: "{{ common_packages }}"
- name: manage user
  import_tasks: user.yml
  tags: user
- name: install firewalld
  yum:
    name: firewalld
- name: firewalld is active and enabled on system startup
  systemd:
    name: firewalld
    state: started
    enabled: yes
- name: setup etckeeper
  import_tasks: etckeeper.yml
  tags: etckeeper
- name: setup ssh
  import_tasks: ssh.yml
  tags: swap
- name: setup fail2ban
  import_tasks: fail2ban.yml
  tags: fail2ban
- name: setup swap
  import_tasks: swap.yml
  when: ansible_memory_mb.swap is undefined
  tags: swap
