---
- name: Update Postfix config
  ansible.builtin.lineinfile:
    path: /etc/postfix/main.cf
    regexp: ^{{ item.key }}\s*=
    line: "{{ item.key }} = {{ item.value }}"
  loop: "{{ postfix_cfg | dict2items }}"
  notify: restart postfix
