---
- name: Install geoip packages
  ansible.builtin.apt:
    name:
      - geoip-bin
      - geoip-database
- name: Download geoip database update script
  ansible.builtin.get_url:
    url: https://mailfud.org/geoip-legacy/geoip_update.sh
    dest: /etc/cron.weekly/geoip_update
    mode: "0755"
- name: Create ssh filter script
  ansible.builtin.template:
    src: ssh/sshfilter.j2
    dest: /usr/local/bin/sshfilter
    mode: "0755"
- name: Set TCP Wrapper(deny)
  ansible.builtin.lineinfile:
    path: /etc/hosts.deny
    regexp: "^sshd: "
    line: "sshd: ALL"
    state: "{{ common_ssh_use_geoip_filter | ternary('present', 'absent') }}"
- name: Set TCP Wrapper(allow)
  ansible.builtin.lineinfile:
    path: /etc/hosts.allow
    regexp: "^sshd: "
    line: "sshd: ALL: spawn /usr/local/bin/sshfilter %a"
    state: "{{ common_ssh_use_geoip_filter | ternary('present', 'absent') }}"
- name: Ensure allow SSH port
  ufw:
    port: "{{ common_ssh_port | string }}"
    proto: tcp
    rule: "{{ common_ssh_ufw_rule }}"
- name: Ensure enable ufw and set default policy
  ufw:
    logging: "on"
    state: enabled
    direction: incoming
    default: deny
