---
- name: Install sudo packages
  ansible.builtin.apt:
    name: sudo
- name: Add admin group
  ansible.builtin.group:
    name: "{{ admin_group_name }}"
- name: Admin group sudo setting
  ansible.builtin.template:
    src: sudo/admin_group.j2
    dest: /etc/sudoers.d/admin_group
    validate: /usr/sbin/visudo -cf %s
    mode: "0644"
