---
- name: Setup swap file
  when: |
    ansible_facts.memory_mb.swap is undefined
    or
    ansible_facts.memory_mb.swap.total == 0
  block:
    - name: Check swapfile exist
      ansible.builtin.stat:
        path: "{{ common_swapfile_path }}"
      register: result
    - name: Create swapfile
      when: not result.stat.exists
      block:
        - name: Create swapfile directory
          ansible.builtin.file:
            path: "{{ common_swapfile_path | dirname }}"
            state: directory
            mode: "0700"
        - name: Create swapfile
          ansible.builtin.file:
            path: "{{ common_swapfile_path }}"
            owner: root
            group: root
            mode: "0600"
            state: touch
        - name: Initilize swapfile
          ansible.builtin.command:
            cmd: dd if=/dev/zero of={{ common_swapfile_path }} bs=1M count={{ common_swap_size | int * 1024 }}
            removes: "{{ common_swapfile_path }}"
        - name: Create swap
          ansible.builtin.command:
            cmd: mkswap {{ common_swapfile_path }}
            removes: "{{ common_swapfile_path }}"
    - name: Ensure mounted swap
      ansible.posix.mount:
        src: "{{ common_swapfile_path }}"
        path: swap
        fstype: swap
        opts: default
        state: present
    - name: Ensure enable swap
      ansible.builtin.command:
        cmd: swapon
        removes: "{{ common_swapfile_path }}"
