---
- name: restart firewalld
  ansible.builtin.systemd:
    name: firewalld
    state: restarted
- name: restart fail2ban
  ansible.builtin.systemd:
    name: fail2ban
    state: restarted
- name: restart rsyslog
  ansible.builtin.systemd:
    name: rsyslog
    state: restarted
- name: restart sshd
  ansible.builtin.systemd:
    name: ssh
    state: restarted
- name: restart glances
  ansible.builtin.systemd:
    name: glances
    state: restarted
    daemon_reload: true
  when: glances_service_setting.running
