---
- name: Verify
  hosts: all
  gather_facts: true
  become: true
  tasks:
    - name: Gather package facts
      ansible.builtin.package_facts:
        manager: auto
    - name: Populate service facts
      ansible.builtin.service_facts:
    - name: Gather user facts
      ansible.builtin.shell:
        cmd: |
          set -eo pipefail
          cat /etc/shadow | jc --shadow
        executable: /usr/bin/bash
      changed_when: false
      register: user_result
    - name: Set registered_users variable
      ansible.builtin.set_fact:
        registered_users: "{{ user_result.stdout | from_json }}"
    - name: Gather group facts
      ansible.builtin.shell:
        cmd: |
          set -eo pipefail
          cat /etc/group | jc --group
        executable: /usr/bin/bash
      changed_when: false
      register: group_result
    - name: Set registered_groups variable
      ansible.builtin.set_fact:
        registered_groups: "{{ group_result.stdout | from_json }}"
    ## パッケージのテスト
    - name: Test  package
      block:
        - name: Assert package
          ansible.builtin.assert:
            that:
              - ansible_facts.packages['etckeeper'] is defined
              - ansible_facts.packages['ufw'] is defined
              - ansible_facts.packages['fail2ban'] is defined
              - ansible_facts.packages['glances'] is defined
            fail_msg: "Some required packages are not installed"
            success_msg: "All required packages are installed"
        - name: Assert utility package
          ansible.builtin.assert:
            that:
              - ansible_facts.packages['tig'] is defined
              - ansible_facts.packages['jq'] is defined
              - ansible_facts.packages['jc'] is defined
              - ansible_facts.packages['strace'] is defined
              - ansible_facts.packages['rclone'] is defined
              - ansible_facts.packages['restic'] is defined
            fail_msg: "Some required utility packages are not installed"
            success_msg: "All required utility packages are installed"
    ## ユーザーのテスト
    - name: Test user
      block:
        - name: Set registered_user_names variable
          ansible.builtin.set_fact:
            registered_user_names: "{{ registered_users | map(attribute='username') | list }}"
        - name: Assert user
          ansible.builtin.assert:
            that:
              - "'simple' in registered_user_names"
              - "'disable_account' in registered_user_names"
              - "'full_set' in registered_user_names"
              - "'admin_user' in registered_user_names"
              - "'not_admin_user' in registered_user_names"
              - "'locked_user' in registered_user_names"
              - "'locked_admin_user' in registered_user_names"
              - "'update_pass_on_create' in registered_user_names"
              - "'update_pass_always' in registered_user_names"
            fail_msg: "Some required users are not registered"
            success_msg: "All required users are registered"
    ## グループのテスト
    - name: Test group
      block:
        - name: Set registered_group_names variable
          ansible.builtin.set_fact:
            registered_group_names: "{{ registered_groups | map(attribute='group_name') | list }}"
        - name: Assert group
          ansible.builtin.assert:
            that:
              - "'app' in registered_group_names"
              - "'adm' in registered_group_names"
            fail_msg: "Some required groups are not registered"
            success_msg: "All required groups are registered"
    ## アカウントロックのテスト
    - name: Test lock user
      block:
        - name: Set locked_user_names variable
          ansible.builtin.set_fact:
            locked_user_names: "{{ registered_users | selectattr('password', 'match', '^!') | map(attribute='username') | list }}"
        - name: Assert lock user
          ansible.builtin.assert:
            that:
              - "'simple' not in locked_user_names"
              - "'disable_account' in locked_user_names"
              - "'full_set' not in locked_user_names"
              - "'admin_user' not in locked_user_names"
              - "'not_admin_user' not in locked_user_names"
              - "'locked_user' in locked_user_names"
              - "'locked_admin_user' in locked_user_names"
              - "'update_pass_on_create' not in locked_user_names"
              - "'update_pass_always' not in locked_user_names"
            fail_msg: "User lock status is not properly configured"
            success_msg: "User lock status is properly configured"
    ## サーバー管理権限のテスト
    - name: Test admin user
      block:
        - name: Set group_members variable
          ansible.builtin.set_fact:
            group_members: "{{ registered_groups | items2dict('group_name', 'members') }}"
        - name: Assert admin user
          ansible.builtin.assert:
            that:
              - "'simple' not in group_members['adm']"
              - "'disable_account' not in group_members['adm']"
              - "'full_set' in group_members['adm']"
              - "'admin_user' in group_members['adm']"
              - "'not_admin_user' not in group_members['adm']"
              - "'locked_user' not in group_members['adm']"
              - "'locked_admin_user' in group_members['adm']"
              - "'update_pass_on_create' not in group_members['adm']"
              - "'update_pass_always' not in group_members['adm']"
            fail_msg: "Admin group membership is not properly configured"
            success_msg: "Admin group membership is properly configured"
    # ファイルのテスト
    - name: Test file
      block:
        - name: Check skeleton user secret env file
          ansible.builtin.stat:
            path: /etc/skel/.secret
          register: skel_result
        - name: Assert file
          ansible.builtin.assert:
            that:
              - skel_result.stat.exists
              - skel_result.stat.mode == '0600'
            fail_msg: "Skeleton user secret env file is not properly configured"
            success_msg: "Skeleton user secret env file is properly configured"
        - name: Check sshfilter script
          ansible.builtin.stat:
            path: /usr/local/bin/sshfilter
          register: sshfilter_result
        - name: Assert file
          ansible.builtin.assert:
            that:
              - sshfilter_result.stat.exists
              - not sshfilter_result.stat.isdir
              - sshfilter_result.stat.executable
            fail_msg: "sshfilter script is not properly installed"
            success_msg: "sshfilter script is properly installed"
        - name: Check geoip database update script
          ansible.builtin.stat:
            path: /etc/cron.weekly/geoip_update
          register: geoip_update_script_result
        - name: Assert geoip database update script
          ansible.builtin.assert:
            that:
              - geoip_update_script_result.stat.exists
            fail_msg: "GeoIP database update script not found"
            success_msg: "GeoIP database update script exists"
        - name: Check geoip database update script
          ansible.builtin.lineinfile:
            path: /etc/cron.weekly/geoip_update
            line: FILES="GeoIP GeoIPv6 GeoIPCity GeoIPCityv6"
          check_mode: true
          register: geoip_update_script_setting_result
        - name: Assert geoip database download file setting
          ansible.builtin.assert:
            that:
              - geoip_update_script_setting_result is not changed
            fail_msg: "GeoIP database download file setting is not properly configured"
            success_msg: "GeoIP database download file setting is properly configured"
        - name: Check Web server docroot symlink
          ansible.builtin.stat:
            path: /home/full_set/www
          register: symlink_result
        - name: Assert docroot symlink
          ansible.builtin.assert:
            that:
              - symlink_result.stat.exists
              - symlink_result.stat.islnk
              - symlink_result.stat.pw_name == 'full_set'
              - symlink_result.stat.gr_name == 'full_set'
              - symlink_result.stat.lnk_source == '/var/www/html'
            fail_msg: "Web server docroot symlink is not properly configured"
            success_msg: "Web server docroot symlink is properly configured"
    ## サービスのテスト
    - name: Test service
      block:
        - name: Assert service(fail2ban)
          ansible.builtin.assert:
            that:
              - ansible_facts.services['fail2ban.service'] is defined
              - ansible_facts.services['fail2ban.service']['state'] == 'running'
              - ansible_facts.services['fail2ban.service']['status'] == 'enabled'
            fail_msg: "fail2ban service is not running or not enabled"
            success_msg: "fail2ban service is running and enabled"
        - name: Assert service(etckeeper)
          ansible.builtin.assert:
            that: ansible_facts.services['etckeeper.service'] is defined
            fail_msg: "etckeeper service is not defined"
            success_msg: "etckeeper service is defined"
        - name: Assert service(vnstat)
          ansible.builtin.assert:
            that:
              - ansible_facts.services['vnstat.service'] is defined
              - ansible_facts.services['vnstat.service']['state'] == 'running'
              - ansible_facts.services['vnstat.service']['status'] == 'enabled'
            fail_msg: "vnstat service is not running or not enabled"
            success_msg: "vnstat service is running and enabled"
        - name: Assert service(glances)
          ansible.builtin.assert:
            that:
              - ansible_facts.services['glances.service'] is defined
              - ansible_facts.services['glances.service']['state'] == 'inactive'
              - ansible_facts.services['glances.service']['status'] == 'disabled'
            fail_msg: "glances service state is not properly configured"
            success_msg: "glances service state is properly configured"
        - name: Gather ufw status
          ansible.builtin.shell:
            cmd: |
              set -eo pipefail
              ufw status verbose | jc --ufw
            executable: /bin/bash
          changed_when: false
          register: result
        - name: Set ufw variable
          ansible.builtin.set_fact:
            ufw: "{{ result.stdout | from_json }}"
        - name: Assert service(ufw)
          ansible.builtin.assert:
            that: ufw.status == 'active'
            fail_msg: "ufw firewall is not active"
            success_msg: "ufw firewall is active"
